version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.0
    - 2.13.4
  - dependency-name: gatsby
    versions:
    - 2.31.0
    - 2.31.1
  - dependency-name: prismjs
    versions:
    - 1.21.0
  - dependency-name: gatsby-cli
    versions:
    - 2.18.0
  - dependency-name: elliptic
    versions:
    - 6.5.3
